### ISSUE TITLE
Update Arma 3

### ISSUE THREAD

**Issue by famfo** [Starz0r/AreWeAntiCheatYet#183] opened 2021-10-19 10:02 UTC
### Game Title

Arma 3

### Status of the Anti-Cheat

❔ Unconfirmed

### Proof of Mention

This discord screenshot is hardly a confirmation that Arma 3 will get support for BattlEye with Proton.

**Comment by doogie544** [comment] 2021-10-20 12:51
Duplicate of #9 #69 and #58 

I would agree with your assessment and in fact one of those duplicates actually post a clarification by the same person who made the initial statement that it was taken out of context. 

However, please make it easier for the poor person who is managing this project and comment on the original issue rather than posting duplicates. It makes it much harder for them if they have to track back through multiple duplicates

**Closed** 2021-12-03 20:16 UTC
Labels: invalid, wontfix
