### ISSUE TITLE
<Game Name Here>

### ISSUE THREAD

**Issue by cccyberwolke** [Starz0r/AreWeAntiCheatYet#87] opened 2021-10-10 22:47 UTC
### Game Title

iRacing

### Game Website

https://www.iracing.com

### Anti-Cheat Software

Easy Anti-Cheat

### Status of the Anti-Cheat

❔ Unconfirmed

### Proof of Mention

N/A

**Comment by Faalagorn** [comment] 2021-10-11 06:26
Duplicate of #78

**Closed as completed** 2021-10-11 06:59 UTC
Labels: duplicate, enhancement
