### ISSUE TITLE
Games with an official EAC testing branch on SteamDB

### ISSUE THREAD

**Issue by Starz0r** [Starz0r/AreWeAntiCheatYet#327] opened 2022-02-05 08:41 UTC
You've may have seen that some games are marked as `Confirmed` or `Supported`, without any external information on it. While I thought Valve might be quicker on this, so I wouldn't have to explain this myself, but it seems they are taking longer than usual to speak on it. Currently a few games have been picked up on SteamDB with either EAC or SteamDeck testing branches. Some of these even have native libraries on Linux for Easy Anti-Cheat. At the moment, we are taking these as actual confirmations to getting proper anti-cheat support until proven otherwise.

The current game list:
-------
Battlefield 2042 - \*[1](https://steamdb.info/app/1517290/depots/?branch=eacc_patch)\* - \*[2](https://steamdb.info/app/1517290/depots/?branch=eacc)\*
SMITE - \*[1](https://steamdb.info/app/386360/depots/?branch=beta_tester)\*
Fall Guys: Ultimate Knockout - \*[1](https://steamdb.info/app/1097150/depots/?branch=closed_beta_1)\*
--Hell Let Loose ~~\*1\*~~ no longer available, branch deleted
Blazing Sails - \*[1](https://steamdb.info/app/1158940/depots/?branch=internaltesting)\*
STAR WARS™: Squadrons - \*[1](https://steamdb.info/app/1222730/depots/?branch=eac_fix)\*

If anyone finds more games on SteamDB, with native Linux libraries for Easy Anti-Cheat, please list them with the proper depot so I can add them!

**Comment by lolsniperftw** [comment] 2022-02-05 13:32
1. I really cant see any linux files or steam deck test branches in your Fall Guys link.
2. In Battlefield 2042 EACC might actually mean (Electronic Arts Compliance & Certification) because I have seen that word on older EA titles.

**Comment by AltF02** [comment] 2022-02-05 21:52
Couldn't we add a fourth status. Something around the lines of "suspected" which clearly differentiates from officially confirmed sources. I could possibly create a PR to implement this

**Comment by Starz0r** [comment] 2022-02-05 22:02
@AltF02 I don't think it's necessary. I'm still committed to trying and keep the list as straightforward as possible. Just didn't think it would take extra time for Valve or any of these companies to officially commit to adding support after adding native Linux libraries to their games.

Right now it's just a waiting game and I don't think it's going to take much longer from Valve on their end.

**Comment by fortressia** [comment] 2022-02-10 01:45
> 1. I really cant see any linux files or steam deck test branches in your Fall Guys link.
> 

Same with Battlefield 2042.

**Comment by pbogut** [comment] 2022-02-23 23:16
Apex Legends has steam_deck branch created 2 hours ago.

https://steamdb.info/app/1172470/depots/?branch=steam_deck

**Comment by Etaash-mathamsetty** [comment] 2022-02-27 04:18
POLYGON has a public test branch (which is public)

**Comment by Newbytee** [comment] 2022-03-01 13:15
I don't think it makes sense to say support is confirmed purely based on that there is a branch on SteamDB. They could be testing it without being set on releasing it. It is very misleading to call something confirmed on this basis, and only serves to create false hope and reduces the trustworthiness of the website.

**Comment by lolsniperftw** [comment] 2022-03-01 13:22
@Newbytee So far all of them merged the test branch to the public branch so I dont see it as misleading.

**Comment by Mar0xy** [comment] 2022-03-03 12:21
the public branch [Patchnote 8231787](https://steamdb.info/patchnotes/8231787/) of Fall Guys from 9 days ago has the EAC linux file included but it seems like it hasn't been enabled yet for some reason who knows if it will be enabled later on

**Comment by r2rX** [comment] 2022-04-18 19:54
Warhammer: Vermintide 2 has a Steam Deck branch (with EAC linux files also included in the standard release but inactive):

https://steamdb.info/app/552500/depots/?branch=steam_deck_testing

**Closed** 2022-05-28 15:07 UTC
