### ISSUE TITLE
Add Gundam Evolution to the list (EAC)

### ISSUE THREAD

**Issue by Cherryda** [Starz0r/AreWeAntiCheatYet#804] opened 2022-09-25 21:48 UTC
### Game Title

GUNDAM EVOLUTION

### Game Website

https://gundamevolution.com/en/

### Anti-Cheat Software

Easy Anti-Cheat

### Status of the Anti-Cheat

😥 Broken

### Proof of Mention

https://steamdb.info/tech/AntiCheat/EasyAntiCheat/

**Comment by Curve** [comment] 2022-09-28 10:17
Duplicate of #786

**Closed by Curve** 2022-09-28 10:17 UTC
