### ISSUE TITLE
LOST ARK

### ISSUE THREAD

**Issue by KZavi** [Starz0r/AreWeAntiCheatYet#235] opened 2021-11-07 11:56 UTC
### Game Title

Lost Ark

### Game Website

https://www.playlostark.com/en-gb

### Anti-Cheat Software

Easy Anti-Cheat

### Status of the Anti-Cheat

❔ Unconfirmed

### Proof of Mention

N/A

**Comment by Cryotize** [comment] 2021-11-07 15:22
Duplicate of #225

**Closed** 2021-11-16 13:33 UTC
Labels: duplicate, enhancement, good first issue
