### ISSUE TITLE
<Apex Legends>

### ISSUE THREAD

**Issue by DerHalbGrieche** [Starz0r/AreWeAntiCheatYet#370] opened 2022-03-02 15:24 UTC
### Game Title

Apex Legends

### Game Website

https://www.ea.com/de-de/games/apex-legends

### Anti-Cheat Software

Easy Anti-Cheat

### Status of the Anti-Cheat

⭐ Supported

### Proof of Mention

https://www.protondb.com/app/1172470

**Comment by doogie544** [comment] 2022-03-02 16:23
Duplicate of

https://github.com/Starz0r/AreWeAntiCheatYet/issues/366

**Closed** 2022-03-03 00:33 UTC
Labels: duplicate, enhancement
