### ISSUE TITLE
<Grand Theft Auto V>

### ISSUE THREAD

**Issue by DuplexEagle** [Starz0r/AreWeAntiCheatYet#415] opened 2022-04-18 05:57 UTC
### Game Title

Grand Theft Auto V

### Game Website

rockstargames.com/gta-v

### Anti-Cheat Software

Other

### Status of the Anti-Cheat

❔ Unconfirmed

### Proof of Mention

N/A

**Comment by Curve** [comment] 2022-04-18 09:05
Duplicate of #292

**Closed** 2022-05-24 11:57 UTC
