### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by bbaster** [Starz0r/AreWeAntiCheatYet#724] opened 2022-08-29 15:04 UTC
Getting the following error while trying to access https://areweanticheatyet.com:

404 Not Found

  -  Code: NoSuchWebsiteConfiguration
  - BucketName: apps-fee64cdb-39ff-462f-8bac-217e28f7df4d
  - RequestId: tx000000000000001d487aa-00630c67d8-3f19b1ab-nyc3c
  - HostId: 3f19b1ab-nyc3c-nyc3-zg03

**Comment by Tosoju** [comment] 2022-08-29 19:06
Can confirm on both firefox and chromium

**Comment by Curve** [comment] 2022-08-29 21:04
@Starz0r ?

**Comment by Starz0r** [comment] 2022-08-29 23:45
Investigated the issue, the DigitalOcean console isn't giving me information, so I'll just assume that it's because the filesystem is too big. Right now we're planning on just moving to GitHub Pages since we have no real clue why this even happened.

**Comment by Starz0r** [comment] 2022-08-30 00:23
@Curve Looked deeper into the issue, seems builds are stalling over the allotted limit because of the new IGDB terms. Currently looking into alternatives.

**Comment by Curve** [comment] 2022-08-30 01:46
I went ahead and setup a github pages workflow & have improved some icon fetching stuff we do in the build phase ^^

**Comment by Starz0r** [comment] 2022-08-30 02:10
Site is currently back up on our DigitalOcean deployment. Will move over to GitHub Pages sometime in the very near future once all bugs are ironed out.

The current outage was caused by a change in the IGDB API Terms, they now require an account, which finally propagated into the builds timing out. We've taken some measures by adding a fallback in case of an untimely outage of IGDB, and we'll be adding some more logging to add better insight to when this happens, so we aren't entirely in the dark.

**Closed by Starz0r** 2022-08-30 02:10 UTC

**Comment by Curve** [comment] 2022-08-30 04:19
I've successfully setup the Github Pages now, in case another outage happens you can try to reach the site via: https://starz0r.github.io/AreWeAntiCheatYet/
