### ISSUE TITLE
Fall Guys (Works on proton now)

### ISSUE THREAD

**Issue by Haxorzz** [Starz0r/AreWeAntiCheatYet#390] opened 2022-03-30 17:41 UTC
### Game Title

Fall guys

### Anti-Cheat Software

Easy Anti-Cheat

### Status of the Anti-Cheat

⭐ Supported

### Proof of Mention

N/A

**Comment by Curve** [comment] 2022-03-30 18:04
Duplicate of #389.

**Closed** 2022-03-30 20:21 UTC
Labels: duplicate, enhancement
