### ISSUE TITLE
MCC nearly confirmed.

### ISSUE THREAD

**Issue by Bitwolfies** [Starz0r/AreWeAntiCheatYet#152] opened 2021-10-13 03:41 UTC
Sorry if this isnt how you submit, but in this steam thread theres a user called "wwm0nkey" who regularly talks to the mcc devs on discord, and has stated the team is looking into adding it, and quote, "wants to see it on the deck"
https://steamcommunity.com/app/976730/discussions/0/2958292387825837160/

**Comment by gardotd426** [comment] 2021-12-11 12:50
That's not remotely enough information to change its status.

"Some random guy claims that some other guy who may or may not work on the game says that they are looking into it." 

That's literally the epitome of "Unconfirmed."

**Comment by Curve** [comment] 2022-05-28 14:50
Due to the .so file being added the game has been marked as planned some time ago.

**Closed by Curve** 2022-05-28 14:50 UTC
